### ISSUE TITLE
Contacting you

### ISSUE THREAD

**Issue by MutantArtCat** [sbtoonz/FisherGuy_Thing#1]
Sorry to do this like this, but it has been brought to my attention that you only respond to Github now, the problem is, the repo I want to respond to is gone and there is no option to DM on Github afaik, so I have no idea how to contact you... Can you help me out with this?

**Comment by sbtoonz** [comment]
https://github.com/VMP-Valheim/MoarBuilds

**Comment by MutantArtCat** [comment]
Thx
